hello/lib/hello_web/router.ex
defmodule HelloWeb.Router do
  use HelloWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Hello.Accounts.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", HelloWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/hello", HelloController, :index
    get "/hello/:messager", HelloController, :hello
    resources "/users", UserController
    get "/chat", ChatController, :index
  end

  scope "/react", HelloWeb do
    pipe_through :browser

    get "/*path", ReactController, :index
  end

  scope "/pm", HelloWeb do
    pipe_through [:browser, :auth]

    get "/", PmController, :index
    post "/", PmController, :login
    post "/logout", PmController, :logout
  end
  scope "/pm", HelloWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/secret", PmController, :secret
  end
end

hello/lib/hello_web/views/layout_view.ex
defmodule HelloWeb.LayoutView do
  use HelloWeb, :view
end

hello/lib/hello_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <!-- <li><a href="/react">React<a></li> -->
            <li><%= link "React", to: "/react" %></li>
            <li><%= link "聊天", to: chat_path(@conn, :index) %></li>
            <li><%= link "管理", to: pm_path(@conn, :index) %></li>
            <li><%= link "用户", to: user_path(@conn, :index) %></li>
            <li><%= link "首页", to: page_path(@conn, :index) %></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>